# Generated by Django 5.0.1 on 2024-01-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='curso_semestre',
            field=models.ManyToManyField(blank=True, null=True, to='core.curso', verbose_name='curso'),
        ),
    ]
