# Generated by Django 5.0.1 on 2024-01-13 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_status_semestre_date_create_semestre_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestre',
            old_name='curso_semestre',
            new_name='cursos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.curso', verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinas',
            field=models.ManyToManyField(to='core.disciplina', verbose_name='disciplinas'),
        ),
    ]
