# Generated by Django 5.0.1 on 2024-01-14 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_curso_semestre_semestre_cursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, null=True, to='core.disciplina', verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.curso', verbose_name='curso'),
        ),
    ]
