# Generated by Django 5.0.1 on 2024-01-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_semestre_disciplinas_alter_disciplina_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='core.curso', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='core.disciplina', verbose_name='disciplina'),
        ),
    ]
