# Generated by Django 5.0.1 on 2024-01-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_disciplina_impar_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='impar_par',
            field=models.CharField(max_length=5),
        ),
    ]
