# Generated by Django 5.0.1 on 2024-01-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_disciplina_impar_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='tempo_exercicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
