# Generated by Django 5.0.1 on 2024-01-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_professor_tempo_exercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='area',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='nivel_graduacao',
            field=models.CharField(blank=True, choices=[('Graduação', 'Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], default='Graduação', max_length=50, null=True),
        ),
    ]
